import type {
  Chat,
  Product,
  Order,
  Notification,
  InventoryItem,
  ActivityLog,
  UserProfile,
  Message,
} from "./types";

export const PRODUCTS: Product[] = [
  {
    id: 1,
    name: "Sony Alpha a7 IV",
    category: "Camera",
    price: 45,
    status: "Available",
    image: "📷",
    imageUrl:
      "https://images.pexels.com/photos/65538/pexels-photo-65538.jpeg?auto=compress&cs=tinysrgb&w=800",
    rating: 4.9,
    reviews: 124,
    owner: { name: "Alex Chen", avatar: "👨‍💻", rating: 5.0, trips: 48 },
    description:
      "Sony Alpha a7 IV la may anh hybrid toi uu, ket hop hoan hao giua chat luong hinh anh tinh 33MP va kha nang quay video 4K 60p chuyen nghiep. Phu hop cho ca chup anh su kien va quay vlog.",
    specs: [
      "Cam bien Full-frame Exmor R 33MP",
      "Lay net theo mat thoi gian thuc",
      "Chong rung 5 truc",
      "ISO 50 - 204,800",
    ],
  },
  {
    id: 2,
    name: 'MacBook Pro M2 - 14"',
    category: "Laptop",
    price: 65,
    status: "Active",
    image: "💻",
    imageUrl:
      "https://images.pexels.com/photos/18105/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=800",
    rating: 4.8,
    reviews: 89,
    owner: { name: "Sarah Miller", avatar: "👩‍💼", rating: 4.9, trips: 32 },
  },
  {
    id: 3,
    name: "Canon EOS R5",
    category: "Camera",
    price: 120,
    status: "Completed",
    image: "📸",
    imageUrl:
      "https://images.pexels.com/photos/51383/photo-camera-subject-photographer-51383.jpeg?auto=compress&cs=tinysrgb&w=800",
    rating: 4.7,
    reviews: 156,
    owner: { name: "Marcus Chen", avatar: "👨‍🔧", rating: 5.0, trips: 61 },
  },
  {
    id: 4,
    name: "4-Person Tent",
    category: "Outdoor",
    price: 15,
    status: "Available",
    image: "⛺",
    imageUrl:
      "https://images.pexels.com/photos/618848/pexels-photo-618848.jpeg?auto=compress&cs=tinysrgb&w=800",
    rating: 4.6,
    reviews: 45,
    owner: { name: "Elena Rodriguez", avatar: "👩‍🎨", rating: 4.8, trips: 28 },
  },
  {
    id: 5,
    name: "Tolkien Box Set",
    category: "Books",
    price: 5,
    status: "Available",
    image: "📚",
    imageUrl:
      "https://images.pexels.com/photos/46274/pexels-photo-46274.jpeg?auto=compress&cs=tinysrgb&w=800",
    rating: 4.9,
    reviews: 234,
    owner: { name: "James Wilson", avatar: "👨‍📚", rating: 5.0, trips: 15 },
  },
  {
    id: 6,
    name: "DJI Air 3 Drone",
    category: "Electronics",
    price: 85,
    status: "Available",
    image: "🚁",
    imageUrl:
      "https://images.pexels.com/photos/3952637/pexels-photo-3952637.jpeg?auto=compress&cs=tinysrgb&w=800",
    rating: 4.8,
    reviews: 167,
    owner: { name: "David Lee", avatar: "👨‍💼", rating: 4.9, trips: 42 },
  },
];

export const CHATS: Chat[] = [
  {
    id: 1,
    name: "Sarah Miller",
    message: "Tôi rất quan tâm đến việc thuê máy chiếu...",
    time: "7m ago",
    active: true,
    avatar: "👩‍💼",
  },
  {
    id: 2,
    name: "Marcus Chen",
    message: "Đơn hàng của bạn đã sẵn sàng giao...",
    time: "1h ago",
    active: false,
    avatar: "👨‍🔧",
  },
  {
    id: 3,
    name: "Elena Rodriguez",
    message: "Cảm ơn vì đã hỗ trợ nhiệt tình!",
    time: "Yesterday",
    active: false,
    avatar: "👩‍🎨",
  },
  {
    id: 4,
    name: "James Wilson",
    message: "Có thể cho tôi biết giá chi tiết hơn không?",
    time: "2h ago",
    active: true,
    avatar: "👨‍📚",
  },
  {
    id: 5,
    name: "Lisa Anderson",
    message: "Tối thiểu phải thuê ít nhất 3 ngày nhé!",
    time: "3h ago",
    active: false,
    avatar: "👩‍🎓",
  },
];

export const MESSAGES: Message[] = [
  // Chat 1 - Sarah Miller
  {
    id: 1,
    chatId: 1,
    content: "Xin chào! Tôi đang tìm hiểu về việc thuê máy chiếu cho sự kiện công ty.",
    timestamp: "2024-04-09 14:30:00",
    sender: "other",
    senderName: "Sarah Miller",
    senderAvatar: "👩‍💼",
  },
  {
    id: 2,
    chatId: 1,
    content: "Tôi rất quan tâm đến việc thuê máy chiếu. Bạn có thể cho tôi biết giá cả và các tùy chọn không?",
    timestamp: "2024-04-09 14:32:00",
    sender: "other",
    senderName: "Sarah Miller",
    senderAvatar: "👩‍💼",
  },
  {
    id: 3,
    chatId: 1,
    content: "Chào Sarah! Vâng, chúng tôi có máy chiếu Sony 4K với giá 45$/ngày. Bạn cần thuê bao lâu?",
    timestamp: "2024-04-09 14:35:00",
    sender: "user",
    senderName: "Nguyễn Văn A",
    senderAvatar: "👨‍💼",
  },
  {
    id: 4,
    chatId: 1,
    content: "Tôi cần thuê khoảng 3 ngày cho sự kiện cuối tuần này. Có thể giao hàng không?",
    timestamp: "2024-04-09 14:37:00",
    sender: "other",
    senderName: "Sarah Miller",
    senderAvatar: "👩‍💼",
  },
  {
    id: 5,
    chatId: 1,
    content: "Tất nhiên rồi! Chúng tôi có thể giao hàng tận nơi. Tổng cộng sẽ là 135$ cho 3 ngày. Ngoài ra, chúng tôi còn cung cấp thêm các phụ kiện như màn chiếu, remote control, và hướng dẫn sử dụng chi tiết.",
    timestamp: "2024-04-09 14:40:00",
    sender: "user",
    senderName: "Nguyễn Văn A",
    senderAvatar: "👨‍💼",
  },
  {
    id: 6,
    chatId: 1,
    content: "Tuyệt vời! Tôi cũng muốn hỏi thêm về chính sách bảo hiểm và bảo hành. Nếu máy chiếu bị hỏng trong quá trình sử dụng thì sao? Và có thể nâng cấp lên phiên bản cao cấp hơn không?",
    timestamp: "2024-04-09 14:45:00",
    sender: "other",
    senderName: "Sarah Miller",
    senderAvatar: "👩‍💼",
  },

  // Chat 2 - Marcus Chen
  {
    id: 6,
    chatId: 2,
    content: "Đơn hàng của bạn đã sẵn sàng giao. Bạn có thể nhận hàng vào sáng mai không?",
    timestamp: "2024-04-09 13:15:00",
    sender: "other",
    senderName: "Marcus Chen",
    senderAvatar: "👨‍🔧",
  },
  {
    id: 7,
    chatId: 2,
    content: "Vâng, tôi có thể nhận hàng vào sáng mai. Cảm ơn bạn đã thông báo!",
    timestamp: "2024-04-09 13:20:00",
    sender: "user",
    senderName: "Nguyễn Văn A",
    senderAvatar: "👨‍💼",
  },

  // Chat 3 - Elena Rodriguez
  {
    id: 8,
    chatId: 3,
    content: "Cảm ơn vì đã hỗ trợ nhiệt tình! Máy ảnh hoạt động rất tốt.",
    timestamp: "2024-04-08 16:45:00",
    sender: "other",
    senderName: "Elena Rodriguez",
    senderAvatar: "👩‍🎨",
  },
  {
    id: 9,
    chatId: 3,
    content: "Rất vui khi được giúp đỡ bạn! Hẹn gặp lại lần sau nhé.",
    timestamp: "2024-04-08 17:00:00",
    sender: "user",
    senderName: "Nguyễn Văn A",
    senderAvatar: "👨‍💼",
  },

  // Chat 4 - James Wilson
  {
    id: 10,
    chatId: 4,
    content: "Tôi đang xem xét thuê một số sách. Có thể cho tôi biết giá chi tiết hơn không?",
    timestamp: "2024-04-09 12:45:00",
    sender: "other",
    senderName: "James Wilson",
    senderAvatar: "👨‍📚",
  },
  {
    id: 11,
    chatId: 4,
    content: "Chắc chắn rồi! Bộ sách Tolkien có giá 5$/ngày. Bạn muốn thuê bao lâu?",
    timestamp: "2024-04-09 12:50:00",
    sender: "user",
    senderName: "Nguyễn Văn A",
    senderAvatar: "👨‍💼",
  },
  {
    id: 12,
    chatId: 4,
    content: "Có lẽ 1 tuần là được. Tôi sẽ nghĩ kỹ hơn.",
    timestamp: "2024-04-09 12:55:00",
    sender: "other",
    senderName: "James Wilson",
    senderAvatar: "👨‍📚",
  },

  // Chat 5 - Lisa Anderson
  {
    id: 13,
    chatId: 5,
    content: "Tôi muốn thuê lều cắm trại cho chuyến đi cuối tuần. Tối thiểu phải thuê ít nhất 3 ngày nhé!",
    timestamp: "2024-04-09 11:20:00",
    sender: "other",
    senderName: "Lisa Anderson",
    senderAvatar: "👩‍🎓",
  },
  {
    id: 14,
    chatId: 5,
    content: "Đúng vậy, chính sách của chúng tôi là tối thiểu 3 ngày cho lều cắm trại. Giá là 15$/ngày.",
    timestamp: "2024-04-09 11:25:00",
    sender: "user",
    senderName: "Nguyễn Văn A",
    senderAvatar: "👨‍💼",
  },
];

export const ORDERS: Order[] = [
  {
    id: "#A102",
    productId: 1,
    productName: "Sony Alpha a7 IV",
    customerName: "Nguyen Van A",
    startDate: "2024-04-10",
    endDate: "2024-04-15",
    totalPrice: 270,
    status: "delivered",
    image: "📷",
  },
  {
    id: "#A103",
    productId: 2,
    productName: 'MacBook Pro M2 - 14"',
    customerName: "Tran Thi B",
    startDate: "2024-04-08",
    endDate: "2024-04-17",
    totalPrice: 585,
    status: "shipped",
    image: "💻",
  },
  {
    id: "#A104",
    productId: 4,
    productName: "4-Person Tent",
    customerName: "Pham Duc C",
    startDate: "2024-04-12",
    endDate: "2024-04-14",
    totalPrice: 30,
    status: "confirmed",
    image: "⛺",
  },
  {
    id: "#A105",
    productId: 6,
    productName: "DJI Air 3 Drone",
    customerName: "Le Minh D",
    startDate: "2024-04-09",
    endDate: "2024-04-18",
    totalPrice: 680,
    status: "pending",
    image: "🚁",
  },
  {
    id: "#A106",
    productId: 3,
    productName: "Canon EOS R5",
    customerName: "Hoang Thu E",
    startDate: "2024-03-20",
    endDate: "2024-03-25",
    totalPrice: 720,
    status: "delivered",
    image: "📸",
  },
];

export const NOTIFICATIONS: Notification[] = [
  {
    id: 1,
    title: "Đơn hàng #A102 đã gửi",
    description: "Đơn hàng của bạn đã được gửi thành công. Kiểm tra trạng thái giao hàng.",
    type: "order",
    time: "2 phút trước",
    read: false,
  },
  {
    id: 2,
    title: "Tin nhắn mới từ Lan",
    description: "Lan đã gửi cho bạn một tin nhắn mới về thời gian nhận thiết bị.",
    type: "message",
    time: "10 phút trước",
    read: false,
  },
  {
    id: 3,
    title: "Khuyến mãi 20% cho camera",
    description: "Chương trình giảm giá 20% cho mảng camera đang diễn ra.",
    type: "promotion",
    time: "1 giờ trước",
    read: true,
  },
  {
    id: 4,
    title: "Hoàn tiền thành công",
    description: "Hoàn tiền cho đơn hàng #A101 đã được xử lý.",
    type: "order",
    time: "3 giờ trước",
    read: true,
  },
  {
    id: 5,
    title: "Cập nhật hệ thống",
    description: "Ứng dụng đã được cập nhật lên phiên bản mới.",
    type: "system",
    time: "1 ngày trước",
    read: true,
  },
];

export const INVENTORY_ITEMS: InventoryItem[] = [
  {
    id: 1,
    name: "Sony Alpha a7 IV",
    category: "Camera",
    quantity: 5,
    price: 45,
    status: "In Stock",
    lastUpdated: "2024-04-09",
  },
  {
    id: 2,
    name: 'MacBook Pro M2 - 14"',
    category: "Laptop",
    quantity: 2,
    price: 65,
    status: "Low Stock",
    lastUpdated: "2024-04-08",
  },
  {
    id: 3,
    name: "Canon EOS R5",
    category: "Camera",
    quantity: 0,
    price: 120,
    status: "Out of Stock",
    lastUpdated: "2024-04-07",
  },
  {
    id: 4,
    name: "4-Person Tent",
    category: "Outdoor",
    quantity: 12,
    price: 15,
    status: "In Stock",
    lastUpdated: "2024-04-09",
  },
  {
    id: 5,
    name: "Tolkien Box Set",
    category: "Books",
    quantity: 8,
    price: 5,
    status: "In Stock",
    lastUpdated: "2024-04-09",
  },
  {
    id: 6,
    name: "DJI Air 3 Drone",
    category: "Electronics",
    quantity: 3,
    price: 85,
    status: "Low Stock",
    lastUpdated: "2024-04-08",
  },
];

export const ACTIVITY_LOGS: ActivityLog[] = [
  {
    id: 1,
    action: "Đăng nhập",
    description: "Đăng nhập từ chrome (192.168.1.1)",
    timestamp: "2024-04-09 14:30:00",
    type: "login",
  },
  {
    id: 2,
    action: "Tạo đơn hàng",
    description: "Tạo đơn hàng #A102 (Sony Alpha a7 IV)",
    timestamp: "2024-04-09 13:15:00",
    type: "order",
  },
  {
    id: 3,
    action: "Gửi tin nhắn",
    description: "Gửi tin nhắn cho Lan",
    timestamp: "2024-04-09 12:45:00",
    type: "message",
  },
  {
    id: 4,
    action: "Cập nhật cài đặt",
    description: "Bật thông báo email",
    timestamp: "2024-04-09 11:20:00",
    type: "settings",
  },
  {
    id: 5,
    action: "Đăng nhập",
    description: "Đăng nhập từ Safari (192.168.1.2)",
    timestamp: "2024-04-08 09:15:00",
    type: "login",
  },
];

export const USER_PROFILE: UserProfile = {
  id: "user-001",
  name: "Nguyễn Văn A",
  email: "user@example.com",
  phone: "0123456789",
  avatar: "👨‍💼",
  joinDate: "2024-01-15",
  address: "123 Đường ABC, Quận 1, TP HCM",
  rating: 4.8,
  completedOrders: 24,
};
